_target_: models.nystromformer.Nystromformer
vocab_size: ${dataset.vocab_size}
embedding_size: 128
num_heads: 2
num_layers: 2
const_vector_length: 25000
n_class: ${dataset.n_class}
device_id: ${general.device_id}