type: PlantDeepSEA
name: ZeaMays
path: ${hydra:runtime.cwd}/data/plant_deepsea/zea_mays
train_data: zea_mays_train.csv
val_data: zea_mays_val.csv
test_data: zea_mays_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 19 