type: VariantEffectPrediction
name: OryzaSativaZS
path: ${hydra:runtime.cwd}/data/variant_effect_prediction/plant/oryza_sativa_zs
train_data: oryza_sativa_zs_train.csv
val_data: oryza_sativa_zs_val.csv
test_data: oryza_sativa_zs_test.csv
variable_length: false
max_seq_len: 1000
vocab_size: 20
n_class: 15